# -*- coding: utf-8 -*-
"""kazan_parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1It_n8_a3gte2KHVZF6U5SOCaWnNnZ-1h
"""
import requests
import csv
import pandas as pd
from collections import defaultdict


file = open('/opt/data/kazan_map','r',encoding='utf-8').read()
soup = BeautifulSoup(file,'xml')


"""Все данные точек с тегами"""

columns = defaultdict(int)
nodes_count = len(soup.findAll('node'))
for node in soup.findAll('node'):
    for k,v in node.attrs.items():
        columns[k] += 1
        for tag in node.findAll('tag'):
            for k,v in tag.attrs.items():
                columns[v] += 1
                break
columns = sorted(columns.items(), key=lambda t: t[1], reverse=True)

columns_to_add = []
for k, v in columns:
    if v > 6000:
        columns_to_add.append(k)
columns_to_add

df = pd.DataFrame(columns=columns_to_add)
for node in tqdm(soup.findAll('node')):
    row = {}
    for k, v in node.attrs.items():
        if k in df.columns:
            row[k] = v 
    for tag in node.findAll('tag'):
        attrs = list(tag.attrs.values())
        if attrs[0] in df.columns:
            row[attrs[0]] = attrs[1]
    df = df.append(row, ignore_index=True)
df.head()

df.to_excel('/opt/data/data.xlsx',sheet_name='data')
